#!/usr/bin/env node
// Syncs the version from package.json into generated TS + public/version.json.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const pkg = JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf8'));
const version = pkg.version;

const generated = `// AUTO-GENERATED by scripts/sync-version.mjs — do not edit by hand.
export const APP_VERSION = '${version}';
export const APP_VERSION_LABEL = 'v${version}';
`;
fs.mkdirSync(path.join(root, 'src/generated'), { recursive: true });
fs.writeFileSync(path.join(root, 'src/generated/appVersion.ts'), generated);

fs.mkdirSync(path.join(root, 'public'), { recursive: true });
fs.writeFileSync(
  path.join(root, 'public/version.json'),
  JSON.stringify({ version, label: `v${version}`, syncedAt: new Date().toISOString() }, null, 2) + '\n',
);

console.log(`Synced version ${version} to src/generated/appVersion.ts and public/version.json`);
